- name: Playbook1
  hosts: Cisco
  gather_facts: no

  tasks:
    - name: Create VLAN
      ios_vlans:
        config:
          - name: VLAN_10_DATA
            vlan_id: 10
            state: active

        state: merged
