- name: Playbook2
  hosts: Cisco
  gather_facts: no

  tasks:
    - name: Delete VLAN
      ios_vlans:
        config:
          - name: VLAN_10_DATA
            vlan_id: 10
            state: active

        state: deleted
